services:
  kafka1:
    image: apache/kafka:3.9.0
    container_name: kafka1
    ports:
      - "9094:9094"
      - "19094:19094"  # External listener port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9094,CONTROLLER://kafka1:9093,EXTERNAL://0.0.0.0:19094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9094,EXTERNAL://localhost:19094
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"  
    volumes:
      - kafka1_data:/var/lib/kafka/data
    networks:
      - kafka_network

  kafka2:
    image: apache/kafka:3.9.0
    container_name: kafka2
    ports:
      - "9096:9096"
      - "19096:19096"  # External listener port
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9096,CONTROLLER://kafka2:9093,EXTERNAL://0.0.0.0:19096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9096,EXTERNAL://localhost:19096
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    volumes:
      - kafka2_data:/var/lib/kafka/data
    networks:
      - kafka_network

  kafka3:
    image: apache/kafka:3.9.0
    container_name: kafka3
    ports:
      - "9098:9098"
      - "19098:19098"  # External listener port
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9098,CONTROLLER://kafka3:9093,EXTERNAL://0.0.0.0:19098
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9098,EXTERNAL://localhost:19098
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    volumes:
      - kafka3_data:/var/lib/kafka/data
    networks:
      - kafka_network

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:

networks:
  kafka_network:
    driver: bridge