
services:
  redis-node-1:
    image: redis:7.4
    container_name: redis-node-1
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - ./redis-config/node-1.conf:/etc/redis/redis.conf
      - ./data/redis-node-1:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.2

  redis-node-2:
    image: redis:7.4
    container_name: redis-node-2
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - ./redis-config/node-2.conf:/etc/redis/redis.conf
      - ./data/redis-node-2:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.11

  redis-node-3:
    image: redis:7.4
    container_name: redis-node-3
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - ./redis-config/node-3.conf:/etc/redis/redis.conf
      - ./data/redis-node-3:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.4

  redis-node-4:
    image: redis:7.4
    container_name: redis-node-4
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6382:6379"
      - "16382:16379"
    volumes:
      - ./redis-config/node-4.conf:/etc/redis/redis.conf
      - ./data/redis-node-4:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.5

  redis-node-5:
    image: redis:7.4
    container_name: redis-node-5
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6383:6379"
      - "16383:16379"
    volumes:
      - ./redis-config/node-5.conf:/etc/redis/redis.conf
      - ./data/redis-node-5:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.6

  redis-node-6:
    image: redis:7.4
    container_name: redis-node-6
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6384:6379"
      - "16384:16379"
    volumes:
      - ./redis-config/node-6.conf:/etc/redis/redis.conf
      - ./data/redis-node-6:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.7

  redis-node-7:
    image: redis:7.4
    container_name: redis-node-7
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6385:6379"
      - "16385:16379"
    volumes:
      - ./redis-config/node-7.conf:/etc/redis/redis.conf
      - ./data/redis-node-7:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.8

  redis-node-8:
    image: redis:7.4
    container_name: redis-node-8
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6386:6379"
      - "16386:16379"
    volumes:
      - ./redis-config/node-8.conf:/etc/redis/redis.conf
      - ./data/redis-node-8:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.9

  redis-node-9:
    image: redis:7.4
    container_name: redis-node-9
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6387:6379"
      - "16387:16379"
    volumes:
      - ./redis-config/node-9.conf:/etc/redis/redis.conf
      - ./data/redis-node-9:/data
    networks:
      redis-cluster:
        ipv4_address: 192.168.1.10

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24